### ISSUE TITLE
TryMyUI reviewer question: differentiated audiences  

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#1]
Current problem: the audience is not differentiated per app. 

Future solution: app devs can qualify for users who have used competitor products and / or easily hone in on their main audience.

**Comment by jeffdomke** [comment]
Per our call with TryMyUI yesterday we are going to experiment with gathering some specific audience data from app devs and seeing how easily we can translate it into the process.

**Comment by hstove** [comment]
We opened a forum thread, but didn't get much actionable feedback. Next step is to reach back out with a more specific ask.

**Comment by jeffdomke** [comment]
https://forum.blockstack.org/t/app-mining-trymyui-audiences/7397

Not getting much input on this from App Miners, moving to icebox.

**Comment by jyudkin1** [comment]
There are a few issues here - besides the end user problem, some apps are solving business solutions, have active users and are not fit for general audiences. 

I fundamentally disagree with the idea of building a mass market product for the 99% from the launch - it goes against every ethos in building and learning. Build for a small sub segment of your target, learn, improve, expand into new segments. 

The sample size is incredibly small - which is not great... possibly having a 100 testers solves this? 

The main issue here is that for forms.id we received feedback that was incredibly useless. For example, "I didn't completely understand the whole concept of the website, but it was probably my fault since I didn't really read the descriptions in the main menu of the website" "The pictures were unappealing to me."  

Finally - we need to optimize for edge cases. So if someone is using IE or whatever environment, it kills the score. 

Also ... If they can't auth into blockstack for whatever reason, again - the rest of the score is hurt. 

Just some issues that the community of miners are likely thinking.

**Comment by avthars** [comment]
Any level of picking who reviews the app would be great. The only current criteria is if they have a real email address.

**Comment by cryptocracy** [comment]
#74

**Comment by jeffdomke** [comment]
Seems like there is some renewed interest here. This is the thread: https://forum.blockstack.org/t/app-mining-trymyui-audiences/7397/16 

Would prefer to continue the discussion here. My original request would still be helpful from my perspective: 

> Only allow testers who are ____________ .
> 
> The blank is one personal descriptor and it can be professional, personal, societal, etc.

> For example:
> Only allow testers who are computer programers.
> Only allow testers who are lawyers.
> Only allow testers who are office workers.
> Only allow testers who are college/university students.
> Only allow testers who are parents.

**Comment by jeffdomke** [comment]
Spoke with TryMyUI again. We can try another approach here: **3 competitive or similar products.** 

Have you currently or previously used _______, _______, or _______ ? 

So, for example, Graphite's might look like: 

Have you currently or previously used **Google Docs**, **Dropbox Paper**, or **Notion**. 

Please reply in this thread and supply the products for your app, then Try My UI will run a test. 🙏

**Comment by dantrevino** [comment]
NoteRiot:
Have you currently or previously used Google Keep, Evernote, or Apple Notes.

**Comment by cryptocracy** [comment]
Cryptocracy:
Have you currently or previously used `Kickstarter`, `GoFundme`, or `Indiegogo`?

**Comment by muneebm** [comment]
XOR Drive: 
Google Drive, Dropbox, or Box

**Comment by avthars** [comment]
> Spoke with TryMyUI again. We can try another approach here: **3 competitive or similar products.**
> 
> `Have you currently or previously used _______, _______, or _______ ?`
> 
> So, for example, Graphite's might look like:
> 
> `Have you currently or previously used Google Docs, Dropbox Paper, or Notion?`
> 
> Please reply in this thread and supply the products for your app, then Try My UI will run a test. 🙏

Afari: Have you currently/ previously used **groups** in **GroupMe, Facebook Messenger, WhatsApp**?

**Comment by kkomaz** [comment]
debut:
Have you currently or previously used Facebook, Twitter, or Google+

**Comment by jackveiga** [comment]
Recall: Have you currently or previously used Google Photos, Dropbox or Flickr?

**Comment by jyudkin1** [comment]
forms.id: Have you currently or previously used Google Forms, Typeform or SurveyMonkey?

**Comment by charlottelucyhall** [comment]
@jeffdomke we feel our app is too niche to have been tested previously but here goes:

Have you currently or previously used Xref, SkillSurvey or Outmatch?

We would be happy for data conscious individuals/ hr managers/ recruiters to be reviewing our app :)

**Comment by BrianQuinn28** [comment]
Utilo:
Have you previously used Quora, Reddit, or Steemit?

**Comment by ferrucc-io** [comment]
keep in touch (kit) have you currently or previously used the Airtable Personal CRM, Affinity CRM or Monica CRM?

**Comment by jehunter5811** [comment]
Graphite - have you currently or previously used Google Docs or Dropbox Paper?

Graphite Publishing - have you currently or previously used WordPress or Ghost blogging solutions?

**Comment by charlottelucyhall** [comment]
@jeffdomke what will the default be if no-one has used any of the similar products?

**Comment by brunohq** [comment]
Blockvault: "Have you currently or previously used 1Password, LastPass, or KeePass?"

**Comment by andresousa** [comment]
Scannie: have you currently or previously used Scannable, Adobe Scan or Scanner App?

**Comment by bodymindarts** [comment]
Misthos:
Casa Keymaster, Electrum Multisig, Copay.io

**Comment by trotolo** [comment]
Hi all, Tim from TryMyUI here. This is a great start! 

For apps that have well-known, widely-used competitors (e.g. Google Photos, Dropbox, Kickstarter etc.) this should work very smoothly. Please make sure that the 3 competitors you list are the ones with the broadest user base in your space. 

In cases where the space is still pretty new and kind of niche, even the main competitors (if there are any) may have a small and hard-to-find audience. What I would suggest is, instead of giving competitors, think of products or services that would be indicative of someone who'd be interested in your app. 

_For example_ - if you were making an app for indexing and mapping hiking trails, we could target people who use REI, Backcountry, and Patagonia. These would be pretty reliable indicators of someone likely to use a hiking app.

**Comment by talhasch** [comment]
Lander:
About.me, WiseIntro, Carrd

**Comment by AC-FTW** [comment]
Stealthy.IM: "Have you currently or previously used Signal, Telegram, or Messenger?"

**Comment by charlottelucyhall** [comment]
Broader options for Zinc: Indeed, Fiverr, Upwork

**Comment by jeffdomke** [comment]
@trotolo checking in on this, any progress on testing these in your platform? Would be ideal to get some feedback soon so we can consider this for May. Thx.

**Comment by kkomaz** [comment]
debut:
Have you currently or previously used duckduckgo, brave, or twitter

**Comment by ViniciusBP** [comment]
BitPatron:
Have you currently or previously used Patreon, Bitcoin, or Reddit

**Comment by jeffdomke** [comment]
Email requesting the final audiences was sent out and this change will affect the May ranking. Moving this issue to done. Thanks for your input everyone.

**Comment by dantrevino** [comment]
@jeffdomke @GinaAbrams how do i update my target apps?

**Comment by GinaAbrams** [comment]
please email trotolo@trymyui.com 🙏
