### ISSUE TITLE
Awario July Points

### ISSUE THREAD

**Issue by Walterion1** [blockstack/app-mining#130]
Hey,
I tried to look at what Mitchell did with Awario and results improved much thanks to him. But as he respectfully doesn't want to be the judge and jury, here are some points, maybe others find them interesting.

I do consult in my daily job but please keep in mind that I am one of the Miners so, my points may be partial. The aim is to help to improve the system we work on.
I'm not looking to removing these as this will not help my app. But it will affect some other apps results, so when I notice these, I felt obligated to let others know.
I propose to others to check these and share their thoughts so we can have a reference for the future. If some are not cool, limit them, and if they are, let others repeat them.
This review took less than 2 hours from me, so not a time-consuming job.
These may interest specially @dantrevino, @cuevasm, @GinaAbrams, @muneeb-ali, @hstove, @jehunter5811, @kkomaz, @jeffdomke and @pstan26

Lander:  
- Tweets from bobbyblaze744 are as irrelevant as removed tweets from Scannie or Radicle, and no visible connection to crypto and tech world. These are many tweets, all in two days and seems copy-paste.
- There are two 200K reaches from unrelated accounts like rap video account, and one is deleted already.
- It seems the only visible change from the previous month is coming from some unrelated accounts with "copy-paste" or "delete-after-post" just to gain reach.
- Without these so-called fake tweets, the reach of this app will decrease from 1.6M to only 39K, something like the previous month of this app.

Lannister:
- The Mention CSV was not complete, and the sum would be 32K, but Mitchell updated it to a new XLS, so it seems correct now, and sum is 602K.

Scannie:
- Like Lannister maybe the file is not complete, but the sum of the current file is 20K (as stated in Awario Data Sheet), but in Draft file is 304K. It should be rechecked to don't lose one's right.

Pden:
- Pden did a fun job in getting reach, but it seems not helpful to an app growth at all, just a fun trick to game the system.
- Mentioning a big name for support, not awareness, and not answering back: https://twitter.com/buffer/status/1143153674040029184 .
- Adding the name to an unrelated conversation: https://twitter.com/cz_binance/status/1143116986810949632
- I would call these honest ones, but it seems repeated in the current and previous month and leads to achieving millions of reach without much activity on Twitter.
- More of these High-Followers-Semi-Unrelated-Chats is omitted as seems useful and honest ones (but still not related to the app again).

BitPatron:
- These tweets came in "screening methodology doc" as blacklisted but not removed from the overall results; without these, the sum will decrease from 264K to 45K. 
- To me, this seems a related account and looks fine, although the only problem is copy-pasting two tweets, 3 minutes apart.
https://twitter.com/Jason__ramsey/status/1143706708855988224
https://twitter.com/Jason__ramsey/status/1143706016447680513

**Comment by friedger** [comment]
One solution could be that mention of the account name do not count towards reach but only having the brand name in the tweet. Currently, I am using my personal account and mention the app name, but I am thinking about using an extra account for the brand to get higher scores. If we change not the rules for awario, it should be mentioned in the documents for best practice that a brand account should be used. 

"delete-after-post" tweets could be programmatically checked. I propose that on the 15th of the next month they still need to be publicly available. For manually checking, it seems that the provided link for mention url do not resolve correctly in the browser, e.g. https://twitter.com/statuses/1142531840105992199

**Comment by cuevasm** [comment]
Thanks Walterion, I'm not going to address these individually again since I did with you over email. I still don't feel comfortable just removing some of these without a concrete list of ok vs. not ok. Herein lies the problem. I've been committed to by at least one App Miner that no matter what I do to screen or what rules we agree on, they will spend resources to game the system because they don't like Awario as an App Reviewer and want it removed. So essentially, this creates an arms race which will quickly become too time-consuming and tricky to scale. 

For now, the best way around this I believe is my proposal to score 1's and zeros for each network, same as getting a score out of 6 (6 possible networks). This encourages a good mix of marketing on different important networks while circumventing the Reach issue that seems to easy to game by those who have committed to that strategy. 

We'll plan to discuss this on the next call.

**Comment by Walterion1** [comment]
I should and will check how system works for the sake of our work. But, I wanted to let others know too.Although I think "valid" miners already know these issues like fake ProductHunt votings, and they just don't want to put a lot of time fighting gamers.
I understand your position on this issue and thanks for the support.
About the binary voting, I think it will not solve the issue much but whatever you choose I'm good.

P.S. Please filter out repetitive bot like tweets from social channel of slack, if it is possible. These made being in the loop of news hard.

**Comment by cuevasm** [comment]
How doesn't it solve it? Pumping fake numbers into the Reach is no longer rewarded in that model, so there's no incentive to do it. And, even if people decide to do that for their own business (say it's working for them), it won't affect Awario scores. I think it exactly solves it.

I can't filter out mentions on that level in Slack

**Comment by Walterion1** [comment]
It leaves the active ones doing good for the community with a 1 just like the ones doing some fake tweets to just get the 1. Maybe a 1 to 4 rating like the proposed NIL works better.
I will be glad to see a test run.

Sorry to here that, so we should wait for them to stop repeating.

**Comment by cuevasm** [comment]
The fake tweets only started because we incentivized Reach. Without a reward to Reach, I doubt people will spend money on fake tweets as they could just as easily send their own free tweet with their own account. I don't think a 1-4 is necessary on each network since there are 6 networks folks would have to hit to get a full score. Again, I do think it makes Awario a score that's harder to differentiate yourself on by a huge amount, but I don't think that's a negative actually, plus it allows you all to continue gathering the data from the interface that should be useful in overall growth. 

The only caveat I was going to propose for this (and I planned on waiting until after broader discussion on the call), was to mandate that to count for a network, the Reach must be greater than zero, i.e. a post on Reddit that received no visibility would not count.

**Comment by Walterion1** [comment]
It can be an improvement with this conditions, the best way to find out is to do a test run and see if it will be fair to the apps you already know are better.

On a personal note, I propose to remove FB from the channels as a minor step on the way of privacy of the users. It may send a good sign.

**Comment by cuevasm** [comment]
I've provided the data for the test run as discussed, we'll go over it on the call as planned. If the community wants to remove Facebook that would be fine, however I think when you consider the statistics, giving it up entirely as a path by which dapps should be looking to grow is pretty hard to justify. Posting publicly from a brand account should have no impact on a user's privacy anyway. We all hate Facebook, but the fact remains that for most, it's probably the single biggest, and at least one of the biggest, ways you could grow your user base.

**Comment by GinaAbrams** [comment]
Discussion is ongoing in #135. Closing.
