### ISSUE TITLE
Product Hunt for App Mining registration

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#164]
We are deprecating Product Hunt for app ranking/scoring. 

The question: Does Product Hunt still add value to the App Mining apps, and Blockstack ecosystem, as a marketing channel and quality bar for apps? 

**Specific proposal** 
New apps must submit a valid Product Hunt page/URL to be completely registered for App Mining. Apps will not be ranked or paid without a valid link. 

**Feedback please**

- Alternate requirement ideas? Certain number of upvotes to start ranking? Valid launch within 3 months of registration? Other ideas? 
- Ways in which this could hurt App Miners or the program? 

Thanks.

**Comment by friedger** [comment]
Make it please a requirement to ensure higher quality over quantity.

**Comment by dkb868** [comment]
> Ways in which this could hurt App Miners or the program?

I think removing the ProductHunt requirement was a great idea, because it allows app developers to take their time with things instead of rushing to have a big launch. 

One strategy that people use to have a successful product launch is to slowly build up an audience and respond to feedback over a few months, then do the big launch. 

If ProductHunt launch was not a requirement, developers could get valuable feedback from TryMyUI and their current users, build an audience (which would also increase their Awario score), and then have a much more successful launch on ProductHunt a few months later. 

The net result of this could be better launches and more traffic to new apps in the long run.

At the same time, I understand why having no launch requirements might encourage people to build low quality apps. But if TryMyUI is already testing for quality apps, then those low quality apps wouldn't get very far anyway.

If someone is determined to add a low quality app to app mining, a ProductHunt launch requirement isn't going to stop them. It takes 5 minutes to launch on ProductHunt.

> Alternate requirement ideas? Certain number of upvotes to start ranking? Valid launch within 3 months of registration? 

Maybe a launch timeline like "launch within 3 months of joining app mining" might be better. Gives them an adequate time frame to execute an amazing launch.
