### ISSUE TITLE
Require miners to provide a blockstack ID

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#170]
**What is the problem you are seeing? Please describe.**
For users, it is unclear how to contact app publishers. 

**How is this problem misaligned with goals of app mining?**
This does not accelerate the adoption because there is little to build trust in the app

**What is the explicit recommendation you’re looking to propose?**
App publishers need to provide a blockstack ID in the web manifest. 

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
When app publishers can use BNS for apps then this becomes obsolete. 

**Additional context**
App ownership is also required for #169

**Comment by hstove** [comment]
I think requiring a Blockstack ID for the purposes of communicating with an app developer does not solve the problem of "how do I contact the app developer", or "how do I trust the developer".

If you have their Blockstack ID, how do you contact them? Do you use a Blockstack messaging app? Which one? Do they have to be registered on all of them?

If you want to trust the app or contact them, there are established patterns here, like a "contact" section on the app. Adding their ID to their manifest doesn't make sense for communications either, since no one would know to look in there, and that is not an established pattern. If an app doesn't provide that, I think that's fine, and that still doesn't mean you can trust the app. If the app wants to build trust, they can construct their app's messaging in a way that builds trust.

**Comment by jeffdomke** [comment]
Sounds like the real solution is: 
> When app publishers can use BNS for apps then this becomes obsolete.

**Comment by friedger** [comment]
Apps like OI App Center or Lander or Debut can show apps to contact the app developers that the app developer has already used (because it is in their profiles).

Furthermore, the DID document can provide service endpoints how to contact the app developers as well.

> and that is not an established pattern
We are here to innovate :-)

![Screenshot from 2019-11-05 19-14-32](https://user-images.githubusercontent.com/1449049/68233951-8899c400-0000-11ea-9c1a-68a67ef58211.png)

Instead of waiting for BNS for apps to be implemented and become an established pattern, the proposal is an easy to execute and verifiable action. Moving from adding a blockstack ID to using BNS for apps should be easier as well.

**Comment by friedger** [comment]
Closing now as app publishing via BNS is not (yet) available.
