### ISSUE TITLE
Drop the formula and compare apps directly

### ISSUE THREAD

**Issue by leoj3n** [blockstack/app-mining#181]
The "Formulas", "Game Theory", and walls of text explaining all that are all confusing and huge barriers to understanding what the heck "App Mining" really is in a short amount of time, unless you are already really passionate about it, which as a developer coming to the idea for the first time I really am not, I'm just interested in building great useful apps. So, that is to say I grok the general concept from the 50-word explanation, but then it gets super hairy and confusing. I know if I try harder I could understand what it is, but still not why it is that way without even more work.

Why not keep it simple and true to the idea, and put apps up against each other? That could be explained as simple as: A vs B recursively, until one comes out on top. I think that works out mathematically, while still remaining practical, but perhaps I am naive (let me know).

You could embody the personal biases of the reviewers into the score, which I think is the way it should be, as long as you are using humans to evaluate, instead of trying to turn those humans into robots that fit into a formula. For instance, if app A is more useful to the user and perhaps easier to use than app B, then let that come through in the fact that app A has a victory over app B. App B might still beat app D, which beat app C but also lost to app A. This gives app B incentive to become more useful and easier to use than app A next round (while also continuing to try and be better than app D), thus encouraging continuous improvement.

This measurable goal of improvement I think should replace the current focus on being first to submit a new app, at least those "make a new app and submit before deadline to get the bonus" types of incentives tend to stress me out. I get the desire to entice new app developers (or just new apps) to join the fray, but I think you might have just as much success promoting the rewards you get from constant development, which is less ostracizing and less one-off. This is just my opinion on the hackathon reward structure, which I think would such restructuring might be more in line with the goals of the App Mining program (thus helping demystify the program to begin with).

So, the idea is to pit apps against each other, A vs B vs C vs D, where there are winners and losers based on direct comparison. Perhaps to limit the sheer number of comparisons needed to create the chain of winners, structure it like a tennis tournament where there are consolation rounds, to limit the breadth of "matches" needed.

I have very little knowledge of the history of the App Mining program, and don't have much of an opinion about it, all I know is I was introduced to it via hackathon and now am part of it. In trying to understand it I found it to be overly complex and wish it worked more simply like the way I'm explaining it here. I understand more embedded people may have ideas on why this suggestion might not work, which of course you should share in response.

**Comment by leoj3n** [comment]
The more I look into the "Game Theory" aspect of this system, the more I realize normal people are not going to understand it, and the less that people understand it, the less people are going to trust it. Why not just present reviewers with two apps, and ask them which they think is better? That makes so much more sense without all the smoke and mirrors. It will be obvious when someone is cheating because we can all use common sense, which this "Game Theory" system cannot. It is obvious when an app is better than another, and only for a near tie might your number of social media followers matter, and even then we all know that is BS.

**Comment by cuevasm** [comment]
"It is obvious when an app is better than another" Perhaps your opinion on it is obvious, but basing an entire system on opinion is not what App Mining is about. App Reviewers are bringing in objective measurements to assess apps in a consistent manner. Comparing two apps head to head and choosing the 'better' one is inherently not objective. What are you choosing based on? Interface? Value created? Business model? How do you compare apples to oranges?

Scenario: How would you feel if your brand new app went up against a well established one and then received a poor score because of it? 

How do you pair apps fairly? Randomly certainly doesn't work as how do you 'compare' two totally different apps with different purposes? This system would only be measuring luck of the draw or the seeding, not how usable they are for their users. I don't think directly comparing apps 1:1 is a useful exercise unless all the apps were built with the intent of solving the same problem or are serving the same user.

Also, are you familiar with how TryMyUI scores? https://docs.blockstack.org/develop/app-reviewers.html#trymyui and https://docs.blockstack.org/community/app-miners-guide#recommendations-from-trymyui. Instead of punishing an app simply for what app it had to face in a tournament style, it looks at every app along specific universal vectors that lead to satisfaction for users and puts out numbers that we can then reasonably rank against other apps with completely different goals, users, business models, etc.  

Last, no one needs to understand anything about Game Theory whatsoever to be successful at App Mining - in fact, I would guess the majority of Miners haven't even read the whitepaper. They can simply follow the scoring methodology for the Reviewers and easily understand what moves their score. We rarely receive feedback to the effect of 'I don't understand game theory and so I don't know what to work on in my app for App Mining'. Generally, feedback is all about making the Reviewers more nuanced and more accurate. I personally don't think we should be building App Mining with the intent of keeping it easy to understand. Building apps is complex and there are a lot of factors. A program assessing them should be nuanced and robust. That said, it's honestly pretty simple. Build an app, make it better over time, keep an eye on certain privacy concerns, and do marketing like you would for any another app.

**Comment by cuevasm** [comment]
"It is obvious when an app is better than another" Perhaps your opinion on it is obvious, but basing an entire system on opinion is not what App Mining is about. App Reviewers are bringing in objective measurements to assess apps in a consistent manner. Comparing two apps head to head and choosing the 'better' one is inherently not objective. What are you choosing based on? Interface? Value created? Business model? How do you compare apples to oranges?

Scenario: How would you feel if your brand new app went up against a well established one and then received a poor score because of it? 

How do you pair apps fairly? Randomly certainly doesn't work as how do you 'compare' two totally different apps with different purposes? This system would only be measuring luck of the draw or the seeding, not how usable they are for their users. I don't think directly comparing apps 1:1 is a useful exercise unless all the apps were built with the intent of solving the same problem or are serving the same user.

Also, are you familiar with how TryMyUI scores? https://docs.blockstack.org/develop/app-reviewers.html#trymyui and https://docs.blockstack.org/community/app-miners-guide#recommendations-from-trymyui. Instead of punishing an app simply for what app it had to face in a tournament style, it looks at every app along specific universal vectors that lead to satisfaction for users and puts out numbers that we can then reasonably rank against other apps with completely different goals, users, business models, etc.  

Last, no one needs to understand anything about Game Theory whatsoever to be successful at App Mining - in fact, I would guess the majority of Miners haven't even read the whitepaper. They can simply follow the scoring methodology for the Reviewers and easily understand what moves their score. We rarely receive feedback to the effect of 'I don't understand game theory and so I don't know what to work on in my app for App Mining'. Generally, feedback is all about making the Reviewers more nuanced and more accurate. I personally don't think we should be building App Mining with the intent of keeping it easy to understand. Building apps is complex and there are a lot of factors. A program assessing them should be nuanced and robust. That said, it's honestly pretty simple. Build an app, make it better over time, keep an eye on certain privacy concerns, and do marketing like you would for any another app.

**Comment by jeffdomke** [comment]
@leoj3n welcome to App Mining. I agree the info is complex and the App Mining team should do a better job of communicating clearly. 

I'm not sure how to respond to the "walls of text" style commentary. If you think you have a design for a clearly superior reviewer, and that would involve removing all other reviewers and altering the scoring formulas: First, I think that is really cool, 👏 for such a bold idea. Second, I really couldn't really respond to that without much, much more detail. For example, I have an open design proposal here: https://github.com/blockstack/app-mining/issues/174 that involves more detail for a smaller change. 

I can't see how this community could evaluate, or accept, a proposal like this without all that detail. As we have learned most designs can be abused, gamed, and are difficult to run. I expect yours is as well but I need more details before I can even weigh in. Thx!

**Comment by leoj3n** [comment]
Seems to me the game theory just introduces arbitrary numbers and the results will still contain the inherent biases of the reviewers; all it affords you is a way to explain it away without actually eliminating it. Sorry if I'm attacking something you feel the need to defend because of the energy and resources you have already put into thinking about and developing this complex system. My point is you could accomplish the same without a complex system that puts up barriers to entry.

If any sports tournament worked this way probably nobody would participate. I just don't see it working out or being attractive in the long run. I know it might hurt to hear an opinion like that.

The idea comes from seeing my app reviewed by TryMyUI videos uploaded by random reviewers. It's cool that they want to tell me how to improve the app but most of us developers built the app so we already know its flaws, and there is no point in me watching all these 20 minute uploads that point out the same obvious flaws with the app. Like has been said they are not actual users of the app and are only giving cursory analysis. Their time would be better spent comparing app A vs app B, and then that video would give me a ton more feedback why they liked app B better, for example.

I am considering on making an introductory post or infographic (or even video might be best), that introduces new comers to the current landscape for this system and hurdles of understanding that they will have to overcome (that I had to overcome). Like you said it's not impossible but I'm sure there a lot of developers that don't make it past the hurdles that could with a better and simpler overview than having to try and find a random web page that explains it in addition to a bunch of other stuff that the person never had questions about. It won't be mean or disparaging, just helpful because in the current state with the wallet and STX and where the money comes from and why with App Mining and submitting paperwork, it is a lot to understand and to undertake to get started in addition to building an app with the decentralized tech to begin with, and most of the way through with the exception of the tech you don't understand why you are having to do what you do.

If the goal is to get more people building apps, I see this as a major pain point. If most people are like me they are not necessarily here for the money or the competition, at least not from the outset.

I do think the explanation of it for new app developers coming into this space could be improved. There needs to be some kind of on-boarding and automated outreach via email in my opinion. A lot of the emails I have received are essentially cryptic if you don't understand the initial premise. Perhaps include explanations of what this email is and why, under the body of the actual dynamic email content. For instance the "TryMyUI results" and the "App Mining" meeting invitations, I largely ignored those because I had no idea why I was being sent that stuff for a long time. Most people are busy and don't always drop what their doing to wade through Google search to find out.

Hope that all makes sense and my opinions are not taken as purposely rousing, on the contrary I'm excited at the opportunity to participate and improve the app I submitted as well as submit some more app ideas to compete against myself.

Any rating system you have is going to be flawed, and currently I think it's not understandable unless you squint, and I know you can participate without a degree in game theory, but I think it is a mistake to so heavily weight the system based on something most people aren't going to take the time to understand, unless this really is just an academic experiment with lots of funding, which I accept it very well may be, in which case it make a whole lot more sense to involve game theory.

Perhaps the goal is to develop a "robotic" system that rates apps and has some business value? Or at least you can argue it does, and then sell it to organizations? I guess if that is one of the goals then it may be worth the effort to continue down this path. At any rate I'm sure my opinion here won't matter much unless others pile on in agreement, but I think a lot of those people never make it to this point that I have. I'll try and help change that regardless, as I feel you all are pretty confident to continue down the same game theory path you are on, which I am sure will work out in the long run despite perhaps not being the best (in my opinion at least).

As I hope I made clear from the outset, I'm not trying to tear down what you have built, just want to share my feedback that it does not resonate with me in the current state as a user. Thanks!

**Comment by leoj3n** [comment]
Let me now reply to @cuevasm as he addressed me with some more direct questions:

> Scenario: How would you feel if your brand new app went up against a well established one and then received a poor score because of it?

I understand that currently TryMyUI is not the only way you rate apps, although that is what I first experienced when looking into this (I was very surprised to see humans uploading videos about my app!), but if there was a video where a nice reviewers voice explained why they like the more established app better than the one I submitted I would be fine with that.

> How do you pair apps fairly? Randomly certainly doesn't work

Yes, in this imaginary system of mine, I did imagine eventually it would make sense or be necessary to put apps into categories. The system I proposed would have its own complexities I am sure you can imagine as someone who thinks about this but would be easier to understand from the outset for normal people looking on from the outside. I wanted to keep the proposal as dead simple as possible, with the understanding that it would evolve over time, but remain much simpler than the arbitrary values and fractional weights of the current game theory approach.

> Also, are you familiar with how TryMyUI scores?

I did find these documents eventually. Yes, they were helpful in explaining things. It gave me the feeling that the complicated system is meant more to keep the big apps fighting over the lion share of the profits, it these somewhat arbitrary metrics gives you a way to pacify their voices and keep them calm. I know that might be a stretch but that is kind of what it feels like, unless like I said this is all an academic experiment.

> Last, no one needs to understand anything about Game Theory whatsoever

To your last point, I appreciate that you can participate unknowingly like I have been for many months now. I'm not so sure that is a good thing however.

> 'I don't understand game theory and so I don't know what to work on in my app for App Mining'

That is not exactly what I was saying, I know exactly what to work on in my app, and I think almost ever developer here does, without the help of some budget reviewer. Most of the apps are clones of already successful apps like Gmail, Slack, or Evernote... It's easy enough to take one look at the closed source app you are emulating to see what features you are lacking. Don't need this overly complicated system to tell you that. Ridiculous, at least your point is in my opinion. Would get much more value out of understanding why a user liked app A over app B.

**Comment by njordhov** [comment]
> That said, it's honestly pretty simple. Build an app, make it better over time, keep an eye on certain privacy concerns, and do marketing like you would for any another app.

@cuevasm Do you have examples of recent apps that launched in lower ranks and later successfully made it into top 20?

**Comment by jeffdomke** [comment]
Assuming we can drop this ticket and keep conversation going over at https://github.com/blockstack/app-mining/issues/185 which has a more complete proposal? Closing, will happily reopen if needed.
