### ISSUE TITLE
Remove sponsored articles from News/Blog reach for Awario

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#190]
**What is the problem you are seeing? Please describe.**
Sponsored articles on a news page or blog are counted towards news/blog reach in awario.

**How is this problem misaligned with goals of app mining?**
The News/Blog category is meant to be true publications. Sponsored articles are not true publications in the sense that the owner of the page takes responsibility for the content.

**What is the explicit recommendation you’re looking to propose?**
Add this rule to awario documentation. Encourage community to verify and flag such articles.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
Keeping Reach a score that is hard to game and doesn't have obvious holes to exploit

**Comment by cuevasm** [comment]
Can you link some examples? My concern with this suggestion is that it's sometimes very hard to separate sponsored articles from regular. If people want to pay for placements in publications, I don't think that's necessarily a bad thing, it could be a great marketing strategy for them and I don't know if App Mining should get into determining what is right for each app. 

Removing Medium was due to obvious issues with how the Reach was calculated.
The suggestion to remove Meetup is due to obvious misclassification.

Not sure sponsored articles hit either of those clear reasons, but happy to understand what the community thinks about paid placement. Then, more importantly, I'd like to hear a plan to reasonably enforcing that reliably at scale given not every outlet marks this and it's easy to find those that don't (especially in the pay to play crypto world).

**Comment by friedger** [comment]
@cuevasm Sponsored articles are articles that are marked as sponsored by the published. 

While this is great for marketing, it is not great for counting reach of real publications.

**Comment by friedger** [comment]
Examples:
* https://www.criptonoticias.com/comunidad/300-aplicaciones-descentralizadas-blockstack-conocelas
* https://zycrypto.com/ditch-google-with-these-privacy-first-alternatives-built-on-top-of-blockstack/

**Comment by cuevasm** [comment]
My question still stands, how could we determine this at scale and what about the many publications that do not mark when an article is sponsored?

**Comment by friedger** [comment]
@cuevasm It is a small step and helps today.

My concern here is that the current rules are not clear about this. Adding this to the rules would help already for the audit period. 

If scale becomes an issue I would hope that the publishers who only publish paid content are not relevant anymore.

**Comment by ViniciusBP** [comment]
> @cuevasm Sponsored articles are articles that are marked as sponsored by the publisher.
> 
> While this is great for marketing, it is not great for counting reach of real publications.

I believe this is not a bug, but a feature. Just as you said, this is great for marketing, so why should it not be incentivized? If in the right niche, it is really effective for adoption and SEO and it also helps Blockstack awareness.

**Comment by cuevasm** [comment]
> It is a small step and helps today.

It's a very difficult small step. This would require me to open every single article and scan it for these indicators. That's hugely time-intensive with quesitonable upside.

**Comment by friedger** [comment]
Add a whistle blower system

Mitchell Cuevas <notifications@github.com> schrieb am Mi., 27. Nov. 2019,
16:23:

**Comment by cuevasm** [comment]
> > @cuevasm Sponsored articles are articles that are marked as sponsored by the publisher.
> > While this is great for marketing, it is not great for counting reach of real publications.
> 
> I believe this is not a bug, but a feature. Just as you said, this is great for marketing, so why should it not be incentivized? If in the right niche, it is really effective for adoption and SEO and it also helps Blockstack awareness.

I tend to agree @ViniciusBP - I see the upside here as much better than a still unclear downside.

**Comment by cuevasm** [comment]
> Add a whistle blower system

And then what? I decide what is sponsored and what isn't? I generally don't like putting something in place that would encourage people to spend their time chasing other people's Mentions like this. I think that's a waste of anyone's time. And, people will just find the paid ones that don't mark it anyway, so why not just treat them all as equal? After all, they are appearing in the publication at the end of day, frankly with probably more visibility than an organic article. 

I personally think people should be allowed to pay for placement if they want. It's how most young companies and apps get started turning the crank on visibility. Maybe you can expand on your issue with this type of marketing/Reach? At the end of the day, everyone pays for placement in one way or another, policing it seems impossible and unnecessary. If someone wants to pay a venue to talk about them, it's their prerogative and it will probably work well for them in real life, shouldn't in App Mining too?

**Comment by friedger** [comment]
It is not about marketing activities. Let everybody create reach as much as possible. 

However, my understanding is that the blended awareness score is about independent/real publications. All social reach is easy to attack as we learnt the hard way.

We should defend the real publications against these kind of attacks. First, by setting the rules, second, by fighting them.

**Comment by njordhov** [comment]
Paid publication is not much different than _self publication_ as a measure of credible reach.

**Comment by cuevasm** [comment]
> We should defend the real publications against these kind of attacks

I think that's a bit extreme, let's be careful with our words. We have no evidence that anyone is 'attacking' anything.  

Second, all of these are _real_ publications. And, almost every publication allows some way for you to pay to be in it in some fashion. Blended Awareness was about stopping the gaming of Reach, that's fundamentally harder to do with the News/Blog category, which is why we chose it. If there were another network where gaming was as hard, we'd likely include that in Reach too. So, your assumed purposed of Blended Awareness is just a bit off in my opinion. Independence of a publication also has little to do with it. I can think of just a handful of truly independent media outlets. 

**The point of this entire reviewer is to encourage apps to become more visible**. With social, we clearly saw the numbers weren't real people (twitter bots, etc.), so we adjusted. But for publications and news outlets, why do we care HOW they got a placement? The point is they did and these are pretty reliably real eyeballs. The app is, therefore, more visible so they should be more successful with an awareness app reviewer.

> Paid publication is not much different than _self publication_ as a measure of credible reach.
Completely disagree in a number of ways that aren't important to this conversation, but happy to engage offline. Paid publication is often some of the most reliable Reach given entire industries are built on making sure eyeballs are real and paid for. And, in the context of Awario, it's irrelevant, as self-publication isn't really a possibility.

**Comment by njordhov** [comment]
> in the context of Awario, it's irrelevant, as self-publication isn't really a possibility.

Yet in issue #189 @cuevasm is troubled by...

> Meetup.com posts register as News/Blog when they are clearly not. This allows some to simply mention their app on an event and get the Reach score of the site.

How come gaining visibility through Meetup is a hole to exploit while paying for publication is not?

**Comment by cuevasm** [comment]
Because Meetup is clearly not a News or Blog site. Paying for awareness is not an exploit or a gap in Awario logic.

**Comment by cuevasm** [comment]
I fundamentally will never agree that paid marketing is somehow wrong or bad. It's a necessity for probably most apps along the way. That's just the base, the enforcement here is also a huge issue that can probably never be done completely or fairly, even I were to agree that for some reason people shouldn't be allowed to do paid media.

**Comment by friedger** [comment]
I think I misunderstood the scoring of Awario.

**Comment by njordhov** [comment]
Related discussion in #208
