### ISSUE TITLE
Awario Exploitation *Serious*

### ISSUE THREAD

**Issue by joshthegreatavenue** [blockstack/app-mining#193]
**What is the problem you are seeing? Please describe.**
Currently, the top winners are no where to be found online despite gaining the MAXIMUM Awario Score. 

From : https://blog.blockstack.org/introducing-awario-app-reviewer/

**Quoted from Blockstack PBC** : 'A common pitfall across all new projects is failing to engage customers and potential customers earlier on. Particularly in crypto, there is a lot of the ‘build it and they will come’ mentality and most projects are failing to find effective ways to market their products outside of a very small echo-chamber (or at all). '

**Then why are high engaging dApp developers are losing Awario scores by many points against this developer?**

The top winners held by pDrive, Secure Calendar, SafeNotes, Photo Vault and Bitcoin4Photos are done by one single developers who I believed has been gaming the Awario system.

My Case against this developer : https://envl.app/joshavenue/hpsQba!MHMKCFUZYOLp3jcT

Check Armig's reddit, he has a redirect link that will bring you to this GitHub : https://github.com/arinyguedes (Probably the same person.)

This person also spams Reddit without Engaging like how other developers would. (https://www.reddit.com/user/Armig/)

Moderate : BitPatron

https://www.linkedin.com/in/vinicius-melo-03a68b134/ <-- **Possible Dev profile.**
https://bitcointalk.org/index.php?topic=2059117.860 <-- **He founded Auctus , which was an exit scam**
The same person who is currently pumping those 13 apps in App Mining
**Auctus Exit Scam Telegram :** https://t.me/AuctusProject

1. This person has a history of running an ICO scam. Raising ~$3,770,005 ditch the project.
2. Does not update his/her apps.
3. Pumps a lot of app into app mining.
4. Not a single person knows this developer who has been taking the top rank consistently. (Against what Awario supposed to be.)
5. Not reachable via email, social media or any other means.

From Awario : 

1. **Reach:** The estimated online Reach of the Mention collected on the brand. Example: How many impressions the tweet mentioning the app actually generated.

2. **Mentions:** These are captured mentions of a brand or app online, on social networks, and on news sites. A ‘Mention’ is registered when the name of the company or brand appears publicly. Example: A tweet mentioning the name of an app in App Mining.

There is no mention of his app anywhere that I could find. 

**How is this problem misaligned with goals of app mining?**
It causes community members to lose faith of the mission we are pursuing, which is high quality dApps. 

**What is the explicit recommendation you’re looking to propose?**
Pause the reward for this developer until Awario's exploitation can be found.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
See Issue #182

**Comment by ViniciusBP** [comment]
Hello Joshua @joshthegreatavenue ,

It is really noble that you are trying your friends' apps but I strongly disagree with the way you are doing. First of all, before you start pointing fingers, you should at least read and understand the App Mining rules. This is the minimum you should do, and you clearly don't understand how Awario scoring works and you are accusing me of exploiting it. If you spend a few minutes to understand, you would understand there is nothing related to an exploitation, the rules were simple and those who didn't do it, it is because they didn't had time to even follow how App mining is evolving. 

If you are wondering if I built all those apps alone, you are wrong, we have 3 different teams working on the same coworking. We share some resources like design and marketing. You are saying that the goal of app mining is to have high quality dApps and this is exactly what we are doing here, it is not coincidence that those apps have better TryMyUI scores and even rated better on your own poll on the chat. 

You are clearly being partial, that's why instead of focusing on showing how you believe my apps are not high quality ones, you are trying to even discuss my other past startups . If you want to discuss it, I am happy to jump on a call with you about that, because this is not the scope here.

Summarizing, you are accusing me of something I am not doing because you didn't read the rules, if you don't agree with the rules, you can open an issue suggesting how you believe it would work better. It is that simple.

**Comment by joshthegreatavenue** [comment]
Great, you said I do not understand how it works.

Can you tell me why you deserved MAX Awario scores for all these apps?

1. pDrive
2. Secure Calendar
3. Moodify (New incoming Blockstack app)
4. DCast
5. Privus Reader
6. Photo Vault
7. SafeNotes

Plus, if I asked you, did you ever buy PH upvotes before for your apps? I am curious.

Since you are the 'Expert'. Can you enlighten me why you are scoring higher than XorDrive? (Even looked like you copied the UX in some aspect.) Read my Doc. 

I cannot seem to find your presence on the internet and in our community. 
I have been around the crypto space for a while, I find it hard to believe that you couldn't keep one project alive (with millions in funding) and now you are managing more than 10? 

Sure, you played by the rules. I will let the community decide. Point finger? Nah, I straight up doubting everything about your apps and the people behind it. Unless, I am proven otherwise that these apps are good for Blockstack ecosystem and community.

**Comment by joshthegreatavenue** [comment]
Great, you said I do not understand how it works.

Can you tell me why you deserved MAX Awario scores for all these apps?

pDrive
Secure Calendar
Moodify (New incoming Blockstack app)
DCast
Privus Reader
Photo Vault
SafeNotes
Plus, if I asked you, did you ever buy PH upvotes before for your apps? I am curious if you able to answer this. Can you prove it? (You said zero exploitation.)

Since you are the 'Expert'. Can you enlighten me why you are scoring higher than XorDrive? (Even looked like you copied the UX in some aspect.) Read my Doc. Or better, show us your Awario dashboard.

I cannot seem to find your presence on the internet and in our community.
I have been around the crypto space for a while, I find it hard to believe that you couldn't keep one project alive (with millions in funding) and now you are managing more than 10?

Sure, you played by the rules. I will let the community decide. Point finger? Nah, I straight up doubting everything about your apps and the people behind it. Unless, I am proven otherwise that these apps are good for Blockstack ecosystem and community.
