### ISSUE TITLE
Publish guide on best practices for app mining 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#21]

**Comment by hstove** [comment]
Draft is done, waiting on some review from @pstan26 . Also would like some feedback from TryMyUI. Looking to publish a first version Wednesday 2019/2/13, even if just with a few teams.

**Comment by kkomaz** [comment]
I believe this would be super helpful.  

I was somewhat frustrated watching these trymyui videos because up to what point are we supposed to hand hold them via our application and

1. Explain what Blockstack is
2. What is a Dapp
3. How do i sign up to blockstack, etc

Especially with certain dapps catered towards blockstack users only how in-depth do we really need to go to?  

Maybe it's just me but it's starting to feel like we're expected to focus less on the building process and more in the education of what blockstack is.  I think thats why the centralized apps that are built on top of blockstack are "winning".  For better or worse they built out the infrastructure explaining what their app does but rarely mentioned the concept of blockstack.  If anything it sounds like the user's are more confused if we mentioned that word.  

## Example

## Landing page text
Debut is a decentralized social networking app powered by Blockstack to help introduce yourself to the Blockstack community

or

Debut is a decentralized social networking app to help introduce yourself to the Blockstack community

### Responses in trymyui
- Is this app a debut app or blockstack app?
- What is blockstack?
- I can't tell if I'm using blockstack or debut
- How do I sign up? (shouldn't the users already have an id at this point?)

The more I hear about this confusion the more I'm tempted to find some plugin like the pied piper [pipey](https://www.youtube.com/watch?v=E2YcOV5C2x4).

**Comment by jeffdomke** [comment]
@hstove and @cuevasm will get this on app.co

**Comment by GinaAbrams** [comment]
@cuevasm has published [V1](https://docs.blockstack.org/community/app-miners-guide.html) of this, we will email app miners as well and request feedback. Closing issue.
