### ISSUE TITLE
Case Blockcred: Non-eligible app?

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#34]
Blockcred looks like a hello world app in terms of using blockstack on login.blockcred.io, only showing the identityAddress after login. Furthermore, the website says "prototype".

The algorithms ranked this app relatively high. Is this in alignment with the long term goals?

**Comment by pstan26** [comment]
Putting a note here that we should investigate this further. Apps can say "prototype", thats no problem, but the broader question may be about leveling up the experience of using Blockstack. If it is hidden or not usable then either they shouldn't get in or there should be an App Reviewer that scores them super low so as to not have them ranked high. 

(Sidenote: In the future, there may be a world where apps may publish their app directly to the blockchain and various app stores may pick them up and highlight them for App Mining automatically.)

**Comment by friedger** [comment]
The main concern for me is that the app does not provide any functionality
with regards to Blockstack other than showing the identity address.

**Comment by MedBTG** [comment]
Where is the logout on this app?

**Comment by kkomaz** [comment]
@pstan26 

Any update on this one?  Curious as the march app mining is coming up

**Comment by AC-FTW** [comment]
@pstan26 it seems like concerns are raised in the forum and on github and generic, non-specific answers are provided but no action is taken. If the App literally does not do anything but let you log in, why is it in the rankings and receiving rewards? Essentially, ideas are now being rewarded instead of implementations of said ideas.

This is similar to the problem of non-publicly available apps being rewarded despite Blockstack saying this is not intended. At what point will someone actually draw a line and take action instead of stating what the rules are supposed to be and continuing to allow them to be broken? Is the desire to attract apps so strong that rules are ignored for the time being or is it just that there are no rules--just intentions that will be codified at some arbitrary point in the future?

**Comment by kkomaz** [comment]
To further add on to this...

<img width="444" alt="screenshot of slack 2-27-19 9-33-35 am" src="https://user-images.githubusercontent.com/8473884/53497871-2ea92d80-3a73-11e9-8315-a87c2cddda31.png">

Sounds like kasstawi has some personal stake or investment in blockcred.  Although it sucks that those votes are being allocated in that fashion it is what it is.

But by his own admission, they are working on "moving all Blockcred infrastructure to Blockstack".  That means it validates @friedger initial thoughts that blockcred, as it stands, is just a "hello world" **blockstack** app.

![screenshot of google chrome 2-27-19 9-38-54 am](https://user-images.githubusercontent.com/8473884/53498042-82b41200-3a73-11e9-92ce-4bc42ca3c1f5.png)

@larrysalibra will the proposed criteria of having a deeper analysis of using blockstack features beyond authentication be included as part of the March app mining?

**Comment by pstan26** [comment]
Hey @ac-ftw Blockcred team has made moves to integrate auth upfront and have it be associated with credentialling. Think they are scrambling to complete everything by the March date. Think it squeaked through initially because it technically had Blockstack Auth. With Larry’s New internet labs coming on as a new app reviewer (he’ll be posting announcement this week) that will dampen the scores of apps that don’t use gaia and other Blockstack tooling and that are live.

I think rules can be enforced in two ways: upfront as apps apply and by scoring. Currently we need to put out a more comprehensive list of requirements because really all that is listed is using Blockstack Auth, if we’re looking at the reality here. 

Some apps may enter the system that are lame ducks with the potential to come alive and evolve. Ideally the incentives created by instantiating better and better app reviewers over time will immediately punish lame duck apps and quickly accelerate usable useful beautiful apps that people love. It could be the case that a very minimal MVP/idea app today gets a lot of attention today for good reasons but due to need to improve app reviewers are getting too much benefit given their stage (which we are announcing a quantum leap next month and took a lot of work to secure with Awario (visibility reviewer) and New Internet Labs (“Good Citizen” reviewer checking for Gaia and other Blockstack tools).

Currently app.co team is scrubbing some of the apps that don’t work with Gina for this next round. Larry’s New Internet Labs will drastically punish apps that just have auth and don’t do anything else with Blockstack tools. If Hank said something about non publicly available apps being listed I may need a refresher what you mean by that, I don’t think there was a direct action item immediately in place there, but if you mean test-flight apps, then yea we should add that to the list of things required for the upcoming round.

There is a lot of legwork that goes into all of this so while it may seem like things are slow moving, a lot of the improvements are feverishly being solved by not introducing requirements enforced by non-app reviewers. It’s really the only way we are going to further decentralize this whole thing (concept mentioned in README a bit) and be allow this to be not governed by one entity. The trade off of finding a reviewer to enforce rules through scoring rather than hastily instantiating it ourselves (and further centralizing App Mining) is that it takes a bit more time and thought, but once’s it’s there people can enter and exit more freely and the problem is closer to being solved in a way that furthers the vision of App Mining becoming a system that operates with, hopefully, no centralized controlling entity motives.

**Comment by AC-FTW** [comment]
@pstan26 

> If Hank said something about non publicly available apps being listed I may need a refresher what you mean by that, I don’t think there was a direct action item immediately in place there, but if you mean test-flight apps, then yea we should add that to the list of things required for the upcoming round.

As I mentioned in my recent [forum post](https://forum.blockstack.org/t/blockstack-february-app-mining-progress-review/7552), you can find Hank's comments about non-publicly available Apps at time-marker 1:20:50 of the video Blockstack posted: https://drive.google.com/file/d/1saxZW0rZVyxYr-INjnZqkpwwA7J2NQQR/view

**Comment by AC-FTW** [comment]
> I think rules can be enforced in two ways: upfront as apps apply and by scoring. Currently we need to put out a more comprehensive list of requirements because really all that is listed is using Blockstack Auth, if we’re looking at the reality here.

@pstan26 two issues--what are the official rules and where are they written for all to see?  How will they be enforced and when?  Once those questions are answered, you have clarity and have set expectations properly and will have fewer disappointed people. 

If Blockstack can't enforce the rules because of decentralization, who will enforce the rules and what process is in place to identify failures to do so?

**Comment by GinaAbrams** [comment]
Hey @AC-FTW  — we’ve added to the FAQ that testflight apps will not qualify moving forward. You can see it [here](https://docs.blockstack.org/develop/appminingfaq#what-qualifies-my-app-to-compete-in-app-mining). 



>  If Blockstack can't enforce the rules because of decentralization, who will enforce the rules and what process is in place to identify failures to do so?
>
We’d like to implement a more thorough QA/audit process. The open question is how. I hear your concerns and agree that it is a priority to proceed. If you have suggestions for a model, would love to discuss. Ideally, we’re able to add more app reviewers that do their jobs well and decrease the impact of single bad actors / exceptions here. 
> Edit: Side note--When an App is new and doesn't integrate a lot of Blockstack features etc., eventually when the platform is larger, it will make sense for it to participate in a separate App Mining Rewards Category for concepts/prototypes/new.
> 
Definitely agree with you on this and categories are a future feature we’d like to implement.

**Comment by AC-FTW** [comment]
Thanks @GinaAbrams, that's helpful and the FAQ seems as good as any place to put it.

After getting more involved with this GitHub last night I've seen that there appear to be up to two more App Reviewers coming into the fold this month or soon. I suspect that @larrysalibra 's effort might be in the best position to ascertain if an App is following a subset of applicable rules (i.e. in trying and examining an App it will quickly become apparent if it is TestFlight or essentially Hello World). His familiarity with the project is also a benefit that TMUI and PH do not share--thus I might actually weigh his effort more heavily than those. 

In thinking about this, there is a near term and long term to consider. Long term, dispute processes and arbiters are worth considering, but in the short term efficiency and Occam's razor suggest the aforementioned model and weight increase.

**Comment by kasstawi** [comment]
> To further add on to this...
> 
> <img alt="screenshot of slack 2-27-19 9-33-35 am" width="444" src="https://user-images.githubusercontent.com/8473884/53497871-2ea92d80-3a73-11e9-8315-a87c2cddda31.png">
> 
> Sounds like kasstawi has some personal stake or investment in blockcred. Although it sucks that those votes are being allocated in that fashion it is what it is.
> 
> But by his own admission, they are working on "moving all Blockcred infrastructure to Blockstack". That means it validates @friedger initial thoughts that blockcred, as it stands, is just a "hello world" **blockstack** app.
> 
> ![screenshot of google chrome 2-27-19 9-38-54 am](https://user-images.githubusercontent.com/8473884/53498042-82b41200-3a73-11e9-92ce-4bc42ca3c1f5.png)
> 
> @larrysalibra will the proposed criteria of having a deeper analysis of using blockstack features beyond authentication be included as part of the March app mining?

Updates: All Blockstack features will be used by end of March. Blockcred has signed a pilot with Zewail University, which means all students will signup for a Blockstack ID to use Blockcred and access their digital certificates.

@kkomaz How would you define a successful Blockstack app?
1. UX/UI
2. Number of users using the app?
3. Number of Blockstack features?

@GinaAbrams @pstan26 @hstove @larrysalibra who should get **more** mining rewards?
Idea Phase (pre-seed
MVP Phase (seed)
Product Market Fit Phase (series A)
Growth Phase (Series B, etc.)

By giving Idea Phase and MVP Phase more mining rewards, you will increase innovation by letting more developers test different use cases but you will also have to fight a lot of fake or churners. 

By giving Product Market Fit Phase and Growth Phase more mining rewards, you will kill innovation and few developers will only use Blockstack because the top 1% will get 80% of the mining rewards.

Should mining rewards go to Idea and MVP phase with strong criteria and Product Market Fit and Growth apply for the Signature Fund?    

Disclosure: I have invested in Blockstack and own a stake in Blockcred

**Comment by AC-FTW** [comment]
> @kkomaz How would you define a successful Blockstack app?
> 
> 1. UX/UI
> 2. Number of users using the app?
> 3. Number of Blockstack features?

@kasstawi I would probably start with: the App Works and doesn't throw internal server errors when I try to use it. Let me know if you want the video of my experience using BlockCred last night--it amounts to a very pretty UI, some edit boxes and a button that leads me to said server error (not trying to trash Blockcred btw, just saying things should probably work or be relegated to competing in that category I mentioned as concept/idea--you might refer to it as pre-seed phase).

You bring up good points--it makes sense to me that Blockstack might want to incentivize Apps in pre-seed and seed phases and compare them differently--though that probably isn't tenable yet. Once they have Series A, they probably ought to be able to make it on their own or the business / model is problematic.

Also, while I appreciate your input here, I don't think you are a bad actor or are in any way required to justify your actions or position (others are sure to disagree). What I really want is a more concrete, definitive set of rules from Blockstack so we can say that Blockcred adheres to the rules or does not. Up until this recent effort, it has been a collective of people with different expectations and interpretations.

Things are measurably improving though.

**Comment by friedger** [comment]
Great to hear that Blockcred will be making good use of Blockstack. I am closing this issue now. 

There are good thoughts and questions in this thread and they should be carried over to new issues.

**Comment by friedger** [comment]
@pstan26 

> because really all that is listed is using Blockstack Auth
It is also listed that hello world apps and apps derived from the tutorial are not eligible.

**Comment by kkomaz** [comment]
@kasstawi 

The intention of my post was not to attack you in any means.  To stay true in the spirit of open voting I think it's fair how and why you vote the way you do.

My purpose of the post was to echo @AC-FTW and clarifying what the criteria is when judging applications and what is weighed more in terms of app mining rewards, which I believe you clearly bring up.

To answer your question what defines a successful Blockstack app... To be honest, based on the rewards so far **I'm not really sure**.

It seems like a lot of apps that built on top of blockstack **first** has had to sacrifice UI/UX usability due to fundamental limitations.  It goes back to a question I asked before in the App miner meeting, "If I'm starting from scratch, is it more beneficial to have a traditional web application, integrate UI/UX easier, and slowly add blockstack features".

I think it's super awesome what you guys are planning to do with on-boarding a significant amount of students to the blockstack community.  Does the potential of influx of users that hasn't integrated blockstack beyond auth/user id display outweigh an application that has low number of users but  has integrated gaia, auth, etc for the month of **February**?  I'm not sure and right now it's hard to tell.

Either way it's a great discussion and something to think about as we iterate each month!

**Comment by friedger** [comment]
@kkomaz @AC-FTW  I think the rules are clear: Payouts are done according to ranking by the app reviewers. There are very limited cases where a dispute can happen- Possible disputes I see: errors in calculations. The eligibility is at the discretion of Blockstack PBC.

Furthermore, we should distinguish between the execution of the program and the feelings what is fair, what is successful, what is against the long-term goals,..

I very much like the question about the phases and tend towards favoring MVPs over prototypes and series A or B apps.

I also tend towards not counting users.

**Comment by friedger** [comment]
Coming back to the initial topic of the issue, as of today the app (at login.blockcred.io) only shows the identity address after login. 

I still think the app should be excluded from the march round. I hope @GinaAbrams will make a wise decision :-) and I am looking forward to end of march!

**Comment by GinaAbrams** [comment]
Updated [app mining FAQ](https://app.co/mining#what-qualifies-my-app-to-compete-in-app-mining) for months moving forward.

**Comment by friedger** [comment]
I think that clarifies the case enough
