### ISSUE TITLE
Case Gladys: Non-eligible app?

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#35]
Gladys requires a Raspberry Pi to use blockstack.

The algorithms ranked this app relatively high. Is this in alignment with the long term goals?

**Comment by pstan26** [comment]
This is a good question I've been thinking about a lot lately. The app + hardware is really cool as its like Amazon Alexa except the user owns their data. I bought a raspberry pi to try this app out. But it may be impossible to continually evaluate this app and for that reason might make sense to remove.

**Comment by thedavidlewis** [comment]
How will it be scored by TMUI if there aren't enough testers with Raspberry Pi? And if there are enough, doesn't that exclude non-technical testers which can skew results.

**Comment by Pierre-Gilles** [comment]
Hey! Founder of Gladys here. 

Gladys is running on pretty anything. Most users run it on a Raspberry Pi for its home automation capability (to add USB dongles, use Bluetooth, ...) but it can run on any computer/VM as well. It's a Node.js program.

Blockstack long-term goal is to incentive developers to build privacy-first product right?

There are not only online products in the world, but also lots of hardware/physical products. 

Isn't that in the long term goal of Blockstack to incentive developers to build any kind of product with their technology, including real-world one?

It would be a little sad if Blockstack limits the scope of allowed apps to basic web stuff.

Maybe it's just the testing process which needs to be improved to handle different kind of products? 

It's not just about Gladys, in the current ranking some apps are iOS apps and people complained it was unfair because an iOS app is harder to test than a web one.

**Comment by AC-FTW** [comment]
@Pierre-Gilles as you mention, we've seen that reviews of mobile applications undergo a different process that results in differences in ranking from Web Apps. The problem is compounded further for Gladys since, but like you I hope that Blockstack is able to find a way to incentivize and review products like yours because they are important, novel on this platform, and require non-trivial effort to launch. Eventually it might be the case that App Mining has multiple branches--i.e. best web app, best mobile app, best embedded device etc.

**Comment by Pierre-Gilles** [comment]
@AC-FTW We are doing a call this week with @GinaAbrams to talk about this topic.

What I'll suggest is that I can simply release a hosted demo version of Gladys, which will be exactly like the one you have at home, just that I will disable "real world" features. The UI will be fully working, but just not controlling real devices.

With this hosted version, TryMyUI testers will just able to review Gladys UI by going to a simple URL, the same way they do it for other web apps.

I think this way it'll be fair for everyone, what do you think of that?

> Eventually it might be the case that App Mining has multiple branches

In the long run definitely! Great to know that you have that in mind :)

Thanks for your answers.

**Comment by friedger** [comment]
@pierre-gilles I think that is the best solution and if that works for Gladys that is great. This is what I proposed in #53:

Apps that provide their main functionality via a mobile app or other hardware should submit an eligible app that users can use in a web browser (maybe with limited functionality).

The preferences in the hosted demo and the real device of the user would then be the same reflected.

**Comment by jeffdomke** [comment]
@GinaAbrams sounds like the next step is an update to our FAQ and adjustment to TryMyUI ranking procedure.

**Comment by GinaAbrams** [comment]
hey @friedger we've update the FAQ section around the ranking algorithm [here](https://app.co/mining#what-qualifies-my-app-to-compete-in-app-mining) to reflect proposed changes. 

For this month's rank and moving forward, it is as follows: Apps may have unique circumstances such that the app cannot be ranked by all the reviewers, for example, apps that require specific hardware. In these cases, reviewers that can review and rank the app will. An app’s final ranking is determined by the average of those reviewers that can fully review the app.

**Comment by friedger** [comment]
I think that clarifies the case enough.
