### ISSUE TITLE
Definition of high-quality

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#36]
There is no clear definition what high-quality means in this repo.

**Comment by pstan26** [comment]
Great point, let's define this precisely. Will circle back soon to do so.

**Comment by mehmetkose** [comment]
App Mining funds non-working apps because they have "fancy" landing pages. We have introduced on the Blockstack.org, and we got $2 this month. What an investment huh? Seems like we will out app mining soon, even Blockstack.
![fup](https://user-images.githubusercontent.com/706678/53148718-a7644180-35bc-11e9-9e19-d97c667ba611.png)

**Comment by jeffdomke** [comment]
Sorry about the super small payout, I'm sure that is frustrating. We're considering some alterations to the payout plan which might help there. 

Also, if you feel like the reviewers are rewarding the wrong stuff, feel free to propose new criteria and reviewers, that is what the repo is for.

**Comment by jeffdomke** [comment]
@friedger is there a specific problem or change you're referencing? On the readme?

**Comment by pstan26** [comment]
We can add a section to the readme under ecosystem activity to be encouraged that highlights qualities of apps that would fit and perform well in App Mining.
