### ISSUE TITLE
Proposal: Do not payout apps that solve the same problem of a higher ranked app

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#37]
This issue is about enforcing diversity of apps and about encouraging collaboration between app developers.

**Comment by markmhx** [comment]
Do you have an example in mind of two apps that are competing head-to-head?

I think we want to see both a diversity of apps _and_ healthy competition between apps that are gunning to solve the same underlying problem for customers. So, I doubt we'd want to programmatically penalize apps that directly compete given their comparative ranking.

However, if we want to promote diversity without penalizing competition, perhaps there's a way in which we can give apps a positive boost for solving a problem that hasn't yet been attempted yet. It could be a "new problem boost", for example, give during the first few months of its debut in App Mining.

**Comment by friedger** [comment]
I started a spreadsheet with competitors to Google Drive, Google Keep and
Google Blogger/Medium at:

https://docs.google.com/spreadsheets/d/1ABMMy9bR_vbdOGtzryNGVzlNmwe32TjywNAM2LIuNaM/edit#gid=0

**Comment by markmhx** [comment]
Sounds good. That spreadsheet looks like it may need to be set to public though?

**Comment by friedger** [comment]
The apps could compete between each other for a share of the amount that the highest ranked app would get. Lets say app A ranks 5th, app B ranks 6th, app C ranks 100th then app A, B and C share $8,192.00  (5th rank's amount): A the most, B a little less than A, C much less than B.

**Comment by pstan26** [comment]
Wouldn't this also dissuade folks from trying to make a massive improvement to the status quo due to revenue share proposed here? Also, aren't folks already incentivized to be unique in order to stand out? The new app booster bonus Mark described seems like a simple way to approach this actually becomes a real problem. My feeling is that if major changes are to be made to App Mining, I'd assume this would be low on the current list as it adds complexity and is not a clear hair on fire problem with how App Mining works today.

**Comment by friedger** [comment]
You propose that app mining should and can give incentives to be unique and
to make massive improvements to the status quo?

For the current reviewers, I don't see any that gives higher score for
uniqueness. And the current ranking shows that in the top 20 there are a
few duplicates.

From a user perspective and for the developer ecosystem, I favor diversity
over competition.

You can make massive improvements by contributing to the best app.

**Comment by thedavidlewis** [comment]
That would be to say that Larry & Sergey could have made the biggest impact by contributing to Altavista, Lycos, Excite, or whichever search engine you would have picked as best. Or Zuck should have gone to work for MySpace or Friendster.

SpringRole doesn't view Note Riot as a competitor. In fact, it may be a partner. And we do more than just that one feature. So which do you pick to be the one to use or do you divide it up among many?

For the proposal to give #100 an equal share to #5, that means that there would be a perverse incentive to create a lot of garbage apps as parasites.

It's rarely a case where there are too many competitors in a field. More often, there aren't enough. The reason that most disappear isn't that they shouldn't have been started (although that is the case for some), they disappear because the best (in tech and/or marketing) win. If you cut down competition, you won't get as many different takes on a problem.

**Comment by benoror** [comment]
> That would be to say that Larry & Sergey could have made the biggest impact by contributing to Altavista, Lycos, Excite, or whichever search engine you would have picked as best. Or Zuck should have gone to work for MySpace or Friendster.

This. Free markets for the worth, let the best prevale.

Also, it's super subjective to try to categorize apps, specially at this early stage, even the ones you mention in you spreadsheet have substantial differences and could end up pivoting into very different markets.

**Comment by friedger** [comment]
@thedavidlewis @benoror We are not in a free market here, it is a very regulated competition for money. Apps in the app mining program get build to be optimized for the algorithms of the distribution of this money. 

My proposal could be more compared to saying that Jeff Bezos should invest in Amazon and Washington Post to achieve his goals. Your proposal would be to say that Jeff Bezos should invest in Amazon, Bol, Alibab and in Washington Post, NY Times,..

> SpringRole doesn't view Note Riot as a competitor. In fact, it may be a partner. And we do more than just that one feature. So which do you pick to be the one to use or do you divide it up among many?

From a data/blockstack perspective, both deal with "Taking notes". The algorithms should encourage that SpringRole and Note Riot cooperate.  

> For the proposal to give #100 an equal share to #5, that means that there would be a perverse incentive to create a lot of garbage apps as parasites.

No, not equal shares.

> Also, it's super subjective to try to categorize apps, specially at this early stage, even the ones you mention in you spreadsheet have substantial differences and could end up pivoting into very different markets.

Washington Post and NY Times have also substantial differences. The algorithms should pick one.

**Comment by friedger** [comment]
> That would be to say that Larry & Sergey could have made the biggest impact by contributing to Altavista, Lycos, Excite, or whichever search engine you would have picked as best. Or Zuck should have gone to work for MySpace or Friendster.

I hope we do not create another Zuck and Larry & Sergey that sucks the data out of us.

**Comment by jeffdomke** [comment]
I tend to agree that this change will create more downsides than upsides. This assumes that we could accurately sort and compare apps, which I don't believe we could. 

Is there a good solution here and/or anyone still feel worth pursuing?
