### ISSUE TITLE
TryMyUI Mobile Apps:  Asking for Impressions on a page that is not the App or even created by the App Authors

### ISSUE THREAD

**Issue by AC-FTW** [blockstack/app-mining#52]
See the screenshot below. Users were asked for their impressions of a page generated by TryMyUI. One of the reviewers got concerned that Stealthy was malware. TryMyUI should either skip this step for mobile apps or link to the mobile apps home/landing page. This creates a problematic disparity between reviewing of mobile and web apps.

![app-mining-feb-review-tmui-issue](https://user-images.githubusercontent.com/16608312/53487110-7e6e0180-3a3f-11e9-8af9-aa3f0832fafe.jpg)

**Comment by friedger** [comment]
I see similar comments (evaluating parts of the internet that is not related to the app) from users 
* that follow a link to blockstack.org
* that don't understand what they should do
* that don't know what blockstack is, what the difference between an app and a website is.
* that see blockstack apps as blockchain apps

To improve the situation I suggest that apps can provide a task that the app is made for, e.g. 
* create a calendar event with friedger.id for next week at 11:00
* send a message to your friend
* create a document with an image
There could be a rating of these tasks that influence the result of the score.

**Comment by trotolo** [comment]
Hey guys, Tim from TryMyUI here. I checked into this and it looks like there was a bug that caused the impression test to be included on these tests. It is not supposed to be part of the flow for mobile apps. We're going to make sure that's fixed for the next round. 

As for the other items, such as testers ending up on the Blockstack site, not knowing what Blockstack is or it's relationship to the app being tested etc., that frankly is the job of your home page to explain. You have to remember the typical person knows much less than you about blockchains, Blockstack, decentralization - and with that in mind, communicate the things they need to know in a way that makes sense to them, right from the start of the experience. 

Many of these apps right now feel like they're built for other developers (GitHub and Trello links right on the front page, really technical talk about how the apps work), but the idea of these tests is to see how users among the general internet-using public respond to the apps. 

Your app's experience needs to be designed for people who don't know what Blockstack is, or what it means that you're "powered by Blockstack," or why they should create a Blockstack account. They won't understand the relationship between your product and Blockstack, or the difference between a web app vs a website. If they go astray during the tests and end up in the wrong place, the number 1 reason for that is that the design didn't set them up for success. 

But when you watch the videos and see where things went off track, you can infer what information is missing, or what pathways pointed them in the wrong direction, and work on fixing those things so that next time around they actually get into the meat of your app. The home page will be really important for this, so spend some time optimizing that and putting the right info and visual cues on there (and eliminating the wrong ones!) 

Hope this helps! -tim

**Comment by AC-FTW** [comment]
Thanks @trotolo.

One thing we noticed is that our January results were all Android testers and our February results were all iOS testers. Another App Dev mentioned 8 tests for his web app--I'm curious what the intention is for mobile Apps, i.e. which of the following can we expect:

- Alternating Android testers one month (4-5), alternating iOS testers the next month (4-5)?
- A mix of Android and iOS testers each month?
- Something else?

Also, TMUI's ability to review the reviewers is really good 👍 (we ended up getting three that talked clearly about their thoughts and one who really didn't, so it was excellent to be able to provide that feedback).

**Comment by jeffdomke** [comment]
Sounds like there is a next step here to reconfirm with @trotolo about the exact expectation for Android vs iOS testing. Last decision I thought was 50/50. @GinaAbrams can you please work on that.

**Comment by trotolo** [comment]
We ran 4 testers on the iOS app and 4 on the Android app for stealthy. It sounds like maybe only the iOS test was copied over for you to view, I’ll check on this and make sure you can view the android ones too

**Comment by AC-FTW** [comment]
@trotolo, here's what I see in the TMUI dashboard when I log in--I suspect you're right:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/16608312/53678001-c2dee480-3c6d-11e9-9060-065c155d0d84.png">

**Comment by jeffdomke** [comment]
@AC-FTW did you ever get the videos you were looking for?

**Comment by AC-FTW** [comment]
Thanks for the reminder @jeffdomke -- I just checked and they were sent to us Mar. 4.

**Comment by GinaAbrams** [comment]
Going to close this, please open a new issue if there are any open questions.
