### ISSUE TITLE
Proposal: Convert DE votes into ratings about product phase

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#54]
**What is the problem you are seeing? Please describe.**
The criteria for up and down votes on DE are not transparent.

**How is this problem misaligned with goals of app mining?**
The scores of DE are not objective, voters tend towards favoring own apps they are invested in. The impact of the votes of a single voter are too high.

**What is the explicit recommendation you’re looking to propose?**
Let votes on DE state in which phase they think an app is (number between 0 and 50 (as a slider?)). The following phases are available:
Idea Phase (pre-seed)
MVP Phase (seed)
Product Market Fit Phase (series A)
Growth Phase (Series B, etc.)

The closer the app toward number 15 the higher the score. 
 

**Long term considerations**
Number 15 can be adjusted in the future depending on the needs of the ecosystem.

**Additional context**
Upvotes are contained in the score of Product Hunt.

This was broad up by @kasstawi in https://github.com/blockstack/app-mining/issues/34#issuecomment-468036375

**Comment by jeffdomke** [comment]
@paulamlb could you please comment on this?

**Comment by paulamlb** [comment]
Hi @friedger ! I don't see the problem that you mentioned exactly as a bug, but an inherent property arising from a community vote of this kind. The idea of imposing a specific set of criteria - although it might make a lot of sense for a different App Reviewer - is misaligned with the core intent of our platform as a space for free and democratic decision-making. You are right that having specific criteria is definitely important for the overall ranking though, and that is why Democracy Earth is not the only App Reviewer. So this is one part of the question.  

We do agree that there is space for improvement in terms of balancing out the impact of a voter deciding to allocate all his votes on a single app. In that sense, we are considering the path of [quadratic voting](https://en.wikipedia.org/wiki/Quadratic_voting), which makes the cost of votes exponentially expensive: 1 vote costs 1, 2 costs 4, 3 costs 9, and so forth. The idea here is that the voter pays with his vote credits for the externality that he is imposing on the ecosystem due to his intense preference, thus leading to a more balanced result in the end and more rational decision-making from voters. In addition, we are also looking into ways of providing more information about the apps inside the platform and reformulating the way we display them - all with the intention of bringing more rationality to the voting process. We find mechanism design and game theoretical approaches to be the most valuable when it comes to making results as fair as possible while maintaining the democratic nature of the platform.

**Comment by friedger** [comment]
Thank you for taking the time to review my proposal. I understand that the change is not desirable.

**Comment by paulamlb** [comment]
Thank you for your proactive engagement @friedger . We highly appreciate ideas coming from the community as we continue refining our platform (some of the best features so far came from community input!). Whenever possible and aligned with our decentralization goals, we will surely implement them :)
