### ISSUE TITLE
Proposal: Remove Product Hunt from App Mining Reviewers

### ISSUE THREAD

**Issue by dantrevino** [blockstack/app-mining#73]
**What is the problem you are seeing? Please describe.**
Product Hunt is basically a measure of how well you launch, **not** app quality over time.

When Blockstack is more popular, newer apps are also going to come on onboard with much more fanfare/awareness.  At this time current Blockstack pioneers will be impacted negatively. In addition,  only 75% of product hunt upvotes are even deemed credible by Product Hunt itself (refer to app mining spreadsheet and do the math).  

**How is this problem misaligned with goals of app mining?**
This does not accelerate the adoption of high quality apps that preserve individual’s fundamental digital rights because it does not reward long term quality and usage of apps.

**What is the explicit recommendation you’re looking to propose?**
Remove product hunt scores from app mining results.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
This could lower the priority for new Blockstack apps from launching on Product Hunt and engaging that indie community directly.  This does not preclude anyone from doing so, however, and if they do, those metrics would be counted by the social metrics of other app reviewers (Awario), presumably.

**Additional context**
NoteRiot in the unfortunate/fortunate position that the app was 'hunted' by a third party, prior to App Mining,  prior to the growth of the community.  I.e. no buildup, no launch, no preparation.  There was a low up take and my ranking suffers from this because NoteRiot PH upvotes, relative to newer apps are lower.  Other pioneering apps will be in this same position over time, even if they are able to coordinate a proper launch.

**Comment by cryptocracy** [comment]
Regarding PH Removal:

I fully agree that they are not the right fit for the needs of the app mining.

Votes are not done monthly, only at time of launch basically.  So if someone hunts your app to soon then you are basically screwed.  

We had a random person hunt Cryptocracy way before it was ready to be evaluated by the general public (it was still in closed beta) ... Literally at the same time were in the middle of changing from our android apk implementation to a pwa implementation, with a total redesign underway, so anyone looking at that time of listing, were almost guaranteed immediately discouraged due to lack of access to original apk and minimum functionality live on new pwa.) 

Now to fix this we have to direct precious time an energy into focusing on marketing, trying to convince people to goto PH and support us, rather then development due to the listing be buried in all the noise of PH and the seemingly no explicit expectation for Blockstack apps to be reviewed by their community. Basically leaving that upto the internal Team which provided no feedback other then arbitrary numbers that have no additional feedback.

**Comment by friedger** [comment]
I'd say "A good app has a good launch". If the launch failed for what ever reasons then that is bad luck.

My understanding is that PH was added to provide a score for how innovative the product/product launch is. Instead of removing PH, I'd add more reviewers such that the weight of the PH score decreases.

**Comment by jeffdomke** [comment]
Here is an alternate proposal: https://github.com/blockstack/app.co/issues/480

**Comment by GinaAbrams** [comment]
A quick update here. We have new info from ProductHunt that if the app has not been featured on their homepage yet, there can be room for that to happen after the fact. Please reach out to their team directly via <appmining@producthunt.com> and they will help. 

I think ProductHunt has the potential to attract new users to the ecosystem, and even if that mainly happens around launches, I don't see that as a bad thing. It is a long term play to help solve some of the problems we see around user education. Apps can be re-hunted over time as well with new releases and versions, which could incentivize ongoing improvements in quality toward those releases.

**Comment by hstove** [comment]
We are going to close this in favor of #85, which includes further improvements to Product Hunt's ranking.
